# Generated by Django 5.0.1 on 2024-02-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('this_prerequisites', models.ManyToManyField(blank=True, null=True, to='website.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('this_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('this_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
                ('this_labs', models.ManyToManyField(blank=True, null=True, to='website.lab')),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='this_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.module'),
        ),
        migrations.AddField(
            model_name='course',
            name='this_modules',
            field=models.ManyToManyField(blank=True, null=True, to='website.module'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('this_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='this_submissions',
            field=models.ManyToManyField(blank=True, null=True, to='website.submission'),
        ),
    ]
