# Generated by Django 4.2.4 on 2024-03-23 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('this_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.program')),
                ('this_submissions', models.ManyToManyField(blank=True, null=True, to='website.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('this_instructors', models.ManyToManyField(blank=True, null=True, to='website.instructor')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='this_course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='this_course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='this_labs',
        ),
        migrations.AddField(
            model_name='assignment',
            name='this_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.lab'),
        ),
        migrations.AddField(
            model_name='lab',
            name='this_assignment',
            field=models.ManyToManyField(blank=True, null=True, to='website.assignment'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='workshop',
            name='this_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.lab'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='this_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.module'),
        ),
        migrations.AddField(
            model_name='program',
            name='this_assignments',
            field=models.ManyToManyField(blank=True, null=True, to='website.assignment'),
        ),
        migrations.AddField(
            model_name='program',
            name='this_modules',
            field=models.ManyToManyField(blank=True, null=True, to='website.module'),
        ),
        migrations.AddField(
            model_name='program',
            name='this_prerequisites',
            field=models.ManyToManyField(blank=True, null=True, to='website.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='this_students',
            field=models.ManyToManyField(blank=True, null=True, to='website.student'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='this_labs',
            field=models.ManyToManyField(blank=True, null=True, to='website.lab'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='this_workshops',
            field=models.ManyToManyField(blank=True, null=True, to='website.workshop'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='this_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.program'),
        ),
        migrations.AddField(
            model_name='lab',
            name='this_instructors',
            field=models.ManyToManyField(blank=True, null=True, to='website.instructor'),
        ),
        migrations.AddField(
            model_name='lab',
            name='this_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.workshop'),
        ),
        migrations.AddField(
            model_name='module',
            name='this_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.program'),
        ),
        migrations.AddField(
            model_name='module',
            name='this_workshops',
            field=models.ManyToManyField(blank=True, null=True, to='website.workshop'),
        ),
        migrations.AddField(
            model_name='submission',
            name='this_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.student'),
        ),
    ]
