# Generated by Django 5.0.1 on 2024-04-23 21:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_program_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='picture',
        ),
        migrations.AddField(
            model_name='instructor',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='website/static/img/instructor/'),
        ),
        migrations.AddField(
            model_name='module',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='website/static/img/module/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='website/static/img/program/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='website/static/img/workshop/'),
        ),
    ]
