# Generated by Django 4.2.5 on 2023-12-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_assignment_course_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='this_course',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='submissions',
            new_name='this_submissions',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='modules',
            new_name='this_modules',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='prerequisites',
            new_name='this_prerequisites',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='thisModule',
            new_name='this_module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='thisCourse',
            new_name='this_course',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='labs',
            new_name='this_labs',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='thisAssignment',
            new_name='this_assignment',
        ),
    ]
